# Generated by Django 6.0.3 on 2026-03-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='submodules',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
