# Generated by Django 6.0.3 on 2026-03-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modules', '0002_module_submodules'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(choices=[('hr', 'HR'), ('finance', 'Finance'), ('production', 'Production'), ('warehouse', 'Warehouse'), ('admin', 'Administration')], max_length=50, unique=True),
        ),
    ]
