# Generated by Django 6.0.3 on 2026-03-25 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_loginhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='GMT Reborn', max_length=200)),
                ('address', models.TextField(blank=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='NPWP')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('fiscal_year_start', models.DateField(blank=True, help_text='Start of fiscal year', null=True)),
                ('fiscal_year_end', models.DateField(blank=True, help_text='End of fiscal year', null=True)),
                ('date_format', models.CharField(default='d/m/Y', help_text='Date format (d/m/Y, m/d/Y, etc)', max_length=20)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profile',
            },
        ),
    ]
