# Generated by Django 6.0.3 on 2026-03-26 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_companyprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GMTSettings',
        ),
    ]
