# Generated by Django 6.0.3 on 2026-03-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_gmtsettings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'verbose_name': 'core_companyprofile', 'verbose_name_plural': 'core_companyprofile'},
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='updated_by_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='currency',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='date_format',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='email',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='fiscal_year_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='fiscal_year_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='logo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='tax_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='updated_at',
            field=models.TextField(),
        ),
        migrations.AlterModelTable(
            name='companyprofile',
            table='core_companyprofile',
        ),
        migrations.DeleteModel(
            name='LoginHistory',
        ),
    ]
