# Generated by Django 6.0.3 on 2026-03-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial_clean'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=50, unique=True)),
                ('nama', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'hr_employee',
            },
        ),
    ]
