# Generated by Django 6.0.3 on 2026-03-31 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_alter_employee_status_karyawan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Agama',
                'verbose_name_plural': 'Agama',
                'db_table': 'hr_agama',
            },
        ),
        migrations.CreateModel(
            name='Pendidikan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, unique=True)),
                ('urutan', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pendidikan',
                'verbose_name_plural': 'Pendidikan',
                'db_table': 'hr_pendidikan',
            },
        ),
        migrations.CreateModel(
            name='PosisiKaryawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Posisi Karyawan',
                'verbose_name_plural': 'Posisi Karyawan',
                'db_table': 'hr_posisi_karyawan',
            },
        ),
        migrations.CreateModel(
            name='StatusKaryawan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Status Karyawan',
                'verbose_name_plural': 'Status Karyawan',
                'db_table': 'hr_status_karyawan',
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='agama',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.agama', verbose_name='Agama'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pendidikan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.pendidikan', verbose_name='Pendidikan'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='posisi_karyawan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.posisikaryawan', verbose_name='Posisi Karyawan'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status_karyawan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.statuskaryawan', verbose_name='Status Karyawan'),
        ),
    ]
