# Generated by Django 6.0.3 on 2026-03-29 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_jabatan_dept_employee_dept_groupdept_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.groupdept'),
        ),
    ]
