# Generated by Django 6.0.3 on 2026-03-31 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0003_agama_pendidikan_posisikaryawan_statuskaryawan_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agama',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pendidikan',
            options={},
        ),
        migrations.AlterModelOptions(
            name='posisikaryawan',
            options={},
        ),
        migrations.AlterModelOptions(
            name='statuskaryawan',
            options={},
        ),
        migrations.AddField(
            model_name='agama',
            name='kode',
            field=models.CharField(default='Islam', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pendidikan',
            name='kode',
            field=models.CharField(default='SMA', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posisikaryawan',
            name='kode',
            field=models.CharField(default='Karyawan', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='statuskaryawan',
            name='kode',
            field=models.CharField(default='Kontrak', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
