# Generated by Django 6.0.3 on 2026-03-29 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_alter_dept_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupdept',
            name='departemen',
        ),
    ]
