# Generated by Django 6.0.3 on 2026-03-31 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0004_alter_agama_options_alter_pendidikan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jabatan',
            name='tugas_utama',
            field=models.TextField(blank=True, null=True, verbose_name='Tugas Utama'),
        ),
    ]
