# Generated by Django 6.0.3 on 2026-04-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0005_jabatan_tugas_utama'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agama',
            options={'verbose_name': 'Agama', 'verbose_name_plural': 'Agama'},
        ),
        migrations.AlterModelOptions(
            name='dept',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Department'},
        ),
        migrations.AlterModelOptions(
            name='groupdept',
            options={'verbose_name': 'Group Department', 'verbose_name_plural': 'Group Department'},
        ),
        migrations.AlterModelOptions(
            name='jabatan',
            options={'verbose_name': 'Jabatan', 'verbose_name_plural': 'Jabatan'},
        ),
        migrations.AlterModelOptions(
            name='pendidikan',
            options={'verbose_name': 'Pendidikan', 'verbose_name_plural': 'Pendidikan'},
        ),
        migrations.AlterModelOptions(
            name='posisikaryawan',
            options={'verbose_name': 'Posisi', 'verbose_name_plural': 'Posisi'},
        ),
        migrations.AlterModelOptions(
            name='statuskaryawan',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Status'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='bpjs_kes_ditanggung',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='BPJS Kesehatan Ditanggung Perusahaan'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bpjs_tk_ditanggung',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='BPJS TK Ditanggung Perusahaan'),
        ),
    ]
