# Generated by Django 6.0.3 on 2026-04-07 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0006_alter_agama_options_alter_dept_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupDept',
            new_name='Division',
        ),
        migrations.AlterModelOptions(
            name='division',
            options={'verbose_name': 'Division', 'verbose_name_plural': 'Divisions'},
        ),
        migrations.RenameField(
            model_name='dept',
            old_name='parent_group',
            new_name='division',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='group',
        ),
        migrations.AddField(
            model_name='employee',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.division', verbose_name='Divisi'),
        ),
        migrations.AlterModelTable(
            name='division',
            table='hr_division',
        ),
    ]
