# Generated by Django 6.0.3 on 2026-04-08 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0008_section_employee_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='jabatan',
            name='dept',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.dept', verbose_name='Departemen (khusus)'),
        ),
    ]
